log_level: info
port: 7880
rtc:
    port_range_start: 10000
    port_range_end: 20000
    use_external_ip: true
    tcp_port: 7881
    udp_port: 7882
keys:
    YOUR-LIVEKITAPIKEY-HERE: YOUR-LIVEKITAPISECRET-HERE
